name: Aplication Django

on: [pull_request]

jobs:
  build:
    env:
      PIPENV_NO_INHERIT: 1
      PIPENV_IGNORE_VIRTUALENS: 1
    runs-on: windowns-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/Setup-python@v1
      with:
        python-version: 3.10
    - name: Instalar Dependências
      run: |
        pip install pipenv
        sync pipenv --dev
    - name: Rodar Testes Automáticos
      run: |
        pipenv run pytest appdjango